services:
  zookeeper:
    container_name: ZookeperOrder
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    container_name: KafkaOrder
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1

      # 1) Escucha en todas las interfaces por el puerto que expones al host
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092

      # 2) Anuncia esa misma dirección/IP a los clientes externos
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.20.10.3:29092

      # 3) Mapea el nombre de listener “PLAINTEXT” a protocolo PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongodb:
    container_name: orderBD
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: UPTC2024
      MONGO_INITDB_DATABASE: CustomerOrderDB
